### ISSUE TITLE
Some questions about the mAP

### ISSUE THREAD

**Issue by Shicoder** [rlit/SupervisedBoF#1]
Hi,
I have read your article,  it's a nice work.  however I did not understand the specific calculation process of the mAP. Could you explain it's calculations in detail or the function "experiment_mAP"? 
Thanks.

**Comment by rlit** [comment]
This function was left out of this package, but accidentally remained in the main script - apologies.
It generates mean-average-precision" (mAP) plot for a selected dictionary over the ground-truth.

**Comment by Shicoder** [comment]
thank you for your help
